name: Install

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Install fisheries gym environment
      run: |
        python setup.py install

