name: Install & Train

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: python -m pip install -r examples/keras-rl/requirements.txt
    - name: Install fisheries gym environment
      run: |
        make install
    - name: Train and test
      run: make test

